// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Wrap the functions.invoke method to suppress 402 payment errors
const originalFunctions = baseClient.functions;
const wrappedFunctions = {
  ...originalFunctions,
  invoke: async (functionName: string, options?: any) => {
    try {
      const result = await originalFunctions.invoke(functionName, options);
      return result;
    } catch (error: any) {
      // Suppress 402 payment errors - they're expected when payment isn't set up
      if (error?.status === 402 || error?.message?.includes('402') || error?.message?.includes('Payment Required')) {
        // Return a structured error response instead of throwing
        return {
          data: null,
          error: {
            status: 402,
            message: 'Payment required',
          },
        };
      }
      // Re-throw other errors
      throw error;
    }
  },
};

// Create wrapped client
export const supabase = {
  ...baseClient,
  functions: wrappedFunctions,
} as typeof baseClient;